### ISSUE TITLE
Does not working with dpd v 0.8.0

### ISSUE THREAD

**Issue by denisowpavel** [deployd/dpd-email#13]
Hello 
I Running existing project with email in resource on deployd version 0.8.0
```
$ dpd --version
0.8.0

$ dpd
starting deployd v0.8.0...

Error loading resources:
Error: Cannot find type "Email" for resource email
    at Array.async.auto.instance [as 2] (/usr/lib/node_modules/deployd/lib/config-loader.js:110:37)
    at listener (/usr/lib/node_modules/deployd/node_modules/async/lib/async.js:493:46)
    at /usr/lib/node_modules/deployd/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (/usr/lib/node_modules/deployd/node_modules/async/lib/async.js:46:24)
    at Object.taskComplete (/usr/lib/node_modules/deployd/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```
For new projects it is running fine, but does not available email on dashboard

After downgrade dpd on version 0.7.0, it is work as usual perfect
```
$ sudo npm install deployd@0.7.0 -g
$ dpd
dpd >
```

**Comment by ericfong** [comment]
Please try to install dpd-email by ```npm install --save dpd-email``` And make sure you have a package.json file

**Comment by ericfong** [comment]
I think this is fixed
